# .github/workflows/run_bot.yml
name: Run Telegram Bot

on:
  push:
    branches:
      - main
  workflow_dispatch: # لتشغيله يدويًا من GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyrogram tgcrypto psycopg2-binary

      - name: Run bot
        env:
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
        run: |
          python bot.py
