name: Run Telegram Bot

on:
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyrogram tgcrypto psycopg2-binary

      - name: Run bot
        env:
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          ADMIN_CHANNEL: ${{ secrets.ADMIN_CHANNEL }}
          PUBLIC_CHANNELS: ${{ secrets.PUBLIC_CHANNELS }}
        run: python bot.py
